// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATYTZkQ5x7OCr0EUQpEcfOFZdQc2rAo28',
    appId: '1:490172964218:web:d7b91532ac32c66b444ac3',
    messagingSenderId: '490172964218',
    projectId: 'locationsharing-1a5bc',
    authDomain: 'locationsharing-1a5bc.firebaseapp.com',
    databaseURL: 'https://locationsharing-1a5bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationsharing-1a5bc.firebasestorage.app',
    measurementId: 'G-WV3WHTBXT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKPdzNStnXmcB9xNmmftGxC0ncv1KNz0',
    appId: '1:490172964218:android:35a204a811394280444ac3',
    messagingSenderId: '490172964218',
    projectId: 'locationsharing-1a5bc',
    databaseURL: 'https://locationsharing-1a5bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationsharing-1a5bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqAhnGiRPq-fjjS36RXAMZREA2OAOLTBg',
    appId: '1:490172964218:ios:264d3583251dfea2444ac3',
    messagingSenderId: '490172964218',
    projectId: 'locationsharing-1a5bc',
    databaseURL: 'https://locationsharing-1a5bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationsharing-1a5bc.firebasestorage.app',
    iosBundleId: 'com.lifelane.lifelane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqAhnGiRPq-fjjS36RXAMZREA2OAOLTBg',
    appId: '1:490172964218:ios:264d3583251dfea2444ac3',
    messagingSenderId: '490172964218',
    projectId: 'locationsharing-1a5bc',
    databaseURL: 'https://locationsharing-1a5bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationsharing-1a5bc.firebasestorage.app',
    iosBundleId: 'com.lifelane.lifelane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATYTZkQ5x7OCr0EUQpEcfOFZdQc2rAo28',
    appId: '1:490172964218:web:dce26178751958f4444ac3',
    messagingSenderId: '490172964218',
    projectId: 'locationsharing-1a5bc',
    authDomain: 'locationsharing-1a5bc.firebaseapp.com',
    databaseURL: 'https://locationsharing-1a5bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationsharing-1a5bc.firebasestorage.app',
    measurementId: 'G-NSD2TKH5Y6',
  );
}
